# Generated by Django 4.0.4 on 2022-06-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0002_saving'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saving',
        ),
    ]
